- src/app/recruit/submitted/page.jsx
- yarn.lock
#8
가입페이지 최종 페이지의 문구를 수정하였고,컴포넌트를 리팩토링 하였습니다.
.
> Feat, Refector(#8)/가입페이지 문구 수정 및 리팩토링

- src/app/recruit/screen/Recruit2.jsx
- src/app/recruit/screen/Recruit3.jsx
#8 
사용자 경험 개선을 위해 제출을 눌러서 중복을 확인하는 것이 아닌, 학번과 전화번호에 중복확인 버튼을 통해 확인하게끔 구현하였습니다.
추가적인 사항은 다음과 같습니다:
- 학번, 전화번호 형식에 어긋나거나, 이미 존재하는 번호일시 false 값 출력
- false값 외에 중복확인으로 검사 완료 후 정보 수정시 '다음' 버튼 비활성화
-
> Feat(#8)/Recruit 학번, 전화번호 중복확인 버튼 구현

- src/app/recruit/submitted/page.jsx
- yarn.lock
#8 
사용자 경험 개선을 위해 제출을 눌러서 중복을 확인하는 것이 아닌, 학번과 전화번호에 중복확인 버튼을 통해 확인하게끔 구현하였습니다.
추가적인 사항은 다음과 같습니다:
- 학번, 전화번호 형식에 어긋나거나, 이미 존재하는 번호일시 false 값 출력
- false값 외에 중복확인으로 검사 완료 후 정보 수정시 '다음' 버튼 비활성화
> Feat(#8)/ Recruit 학번, 전화번호 중복확인 버튼 구현

- .github/workflows/deploy.yml
- Dockerfile
- scripts/deploy.sh
> Fix: docker 빌드 후 s3 로 올리는 방식으로 변경

- Dockerfile
> Fix: cicd 파일 경로 오류 수정

- .github/workflows/deploy.yml
> Fix: cicd codedeploy trigger 추가

- .github/workflows/deploy.yml
> Fix: s3 업로드 파일 수정

- .github/workflows/deploy.yml
> Fix: docker 빌드 확인 코드 삽입

- .github/workflows/deploy.yml
> Fix: tar 추출 수정

- .github/workflows/deploy.yml
#39 
행 간격 잘못 설정해서 CI 오류 나는 문제 해결합니다
> chore: 오타 수정

- .github/workflows/deploy.yml
- appspec.yml
- docker-compose.yml
- scripts/deploy.sh
#39
코드 디플로이에서 배포 시 오류나는 문제를 수정했고, 도커 컨테이너를 이용하여 배포하도록 바꾸었습니다.
> Fix: CI/CD 오류 수정 및 배포 방식 변경

- appspec.yml
#39
- appspec.yml에서 잘못된 위치 참조해서 배포가 안 되는 문제 수정
> fix: 배포 시 스크립트 위치 찾는 부분 수정

- Dockerfile
- docker-compose.yml
#39
- 서버 실행 시 디렉터리 문제로 발생하는 문제 해결
> fix: 서버 실행 오류 수정

- Dockerfile
- appspec.yml
- docker-compose.yml
#39
- next.js 실행 명령어 수정
- workdir 수정
> Fix: 서버 실행 시 디렉터리 문제 해결

- .github/workflows/deploy.yml
- Dockerfile
- scripts/deploy.sh
> fix: 도커 관련 문제 해결

- .github/workflows/deploy.yml
- Dockerfile
- docker-compose.yml
- scripts/deploy.sh
#39
도커 실행 시 제대로 서버 실행이 안 되는 문제 해결
> fix: 도커 실행 문제 해결

- .github/workflows/deploy.yml
- Dockerfile
- docker-compose.yml
> fix: 도커 오류 수정

- .github/workflows/deploy.yml
- Dockerfile
- docker-compose.yml
- scripts/deploy.sh
> fix: 도커 오류 해결

- .github/workflows/deploy.yml
- Dockerfile
- docker-compose.yml
> fix: 도커 빌드 시 오류

- Dockerfile
> fix: 빌드 결과물 수정

- Dockerfile
- docker-compose.yml
> fix: 도커 빌드 시 경로 문제 수정

- Dockerfile
- next.config.mjs
> fix: 정적 배포 삭제

- .github/workflows/deploy.yml
> fix: 컨테이너 실행 확인 후 종료

- Dockerfile
- docker-compose.yml
> fix: 컨테이너 볼륨설정 삭제

- .github/workflows/deploy.yml
- Dockerfile
- docker-compose.yml
> fix: 컨테이너 볼륨 설정 삭제

- src/app/recruit/page.jsx
- src/app/recruit/submit/page.jsx
#8 
가입 완료 문구 변경 및 submitted -> submit 으로 변경
.
.
> Chore(#8)/ recruit submit 이름 변경 및 가입 완료문구 변경

- src/app/study/Header.jsx
- src/app/study/StudyPanel.jsx
- src/app/study/page.jsx
- src/app/study/screen/CreateNewStudy.jsx
- src/app/study/studyData.js
- src/app/study/studyDetail/page.jsx
> #75  
> 브랜치 중복 생성으로 인한 작업물 이동 및 중복 생성된 브랜치 삭제
> Update: 브랜치 중복 생성 실수, 작업물 이동

- src/app/auth/signin/custom/CustomAuthApi.js
- src/app/auth/signin/google/callback/GoogleAuth.js
- src/app/auth/signin/page.jsx
- src/app/auth/signin/screen/AuthFindId.jsx
- src/app/auth/signin/screen/AuthLogin.jsx
- src/app/auth/signin/screen/AuthResetPassword.jsx
- src/app/auth/signin/screen/AuthResetRequest.jsx
- src/components/ui/OtpInput.jsx
- src/components/ui/TransparentInput.jsx
- src/hooks/useAuthApi.js
> Update: 스터디 작동 테스트를 위한 login 구현 PR

- src/app/auth/signin/custom/CustomAuthApi.js
- src/app/auth/signin/google/callback/GoogleAuth.js
- src/app/auth/signin/page.jsx
- src/app/auth/signin/screen/AuthFindId.jsx
- src/app/auth/signin/screen/AuthLogin.jsx
- src/app/auth/signin/screen/AuthResetPassword.jsx
- src/app/auth/signin/screen/AuthResetRequest.jsx
- src/components/ui/OtpInput.jsx
- src/components/ui/TransparentInput.jsx
- src/hooks/useAuthApi.js
#4 
- 로그인 기능에 커스텀 API 연동 및 로딩 UI/에러 처리 개선
- 로그아웃 기능 구현
- 비밀번호 재설정 요청/처리 화면 구현 및 API 연동
- 인증번호 전송 및 인증 UI + 자동 포커스 기능 구현
- 아이디 찾기 페이지 UI 및 API 연동
- TransparentInput 컴포넌트로 입력 필드 재사용화
- Auth 컴포넌트 구조 개선 (분리 및 명칭 변경 등 리팩터링)
- 모바일 대응을 위한 폰트 크기 및 마진 등 UI 스타일 조정
- 공용 주석 제거 및 alert 문구 정리
커스텀 로그인
구글 로그인
아이디 찾기
비밀번호 찾기 1 (이메일, 인증번호)
비밀번호 찾기 2 (비밀번호 변경)
-
> Feat(#4)/ 인증(로그인/비밀번호 재설정) 기능 구현 및 UI/UX 개선

- src/app/auth/signin/page.jsx
> Test study page & refresh token

- src/app/api/signin/route.js
- src/app/auth/signin/custom/CustomAuthApi.js
> Fix: 기존 인증 URL을 프록시 URL로 변경하여 로그인 API 호출 방식 수정

- src/app/api/auth/[route]/route.js
- src/hooks/study/useApplicantDetail.js
- src/hooks/study/useApplicantList.js
- src/hooks/study/useAppliedStudyList.js
- src/hooks/study/useCreatedStudyList.js
- src/hooks/study/useStudyAccessCheck.js
- src/hooks/study/useStudyDetail.js
- src/hooks/study/useStudyList.js
- src/hooks/useAuthApi.js
> #4, #75
> gdgocinha.site -> gdgocinha.com/api 사용을 위한 라우터 프록시 구현 및 study useEffect 수정
-
> Fix(#4, #75)/ router proxy 설정 및 study useEffect 수정

- src/app/api/auth/[route]/route.js
> Fix to correct api url in route.js

- src/app/api/auth/[route]/route.js
>#4
> 프록시 대상 주소 변경 (.com/api -> .site)
> Fix(#4) 프록시 대상 주소 변경

- src/app/api/[route]/route.js
> Fix(#4)/ 프록시 대상 주소 재변경

- .github/workflows/deploy.yml
> fix(workflows): 구글 로그인 관련 변수 추가

- src/app/api/auth/refresh/route.js
> Fix(#4)/ 인증 토큰 API 엔드포인트 변경

- src/hooks/useAuthApi.js
- src/hooks/useAuthenticatedApi.js
- yarn.lock
#4 
- 인증 토큰 관련 API 변수명을 명확하게 수정하여 코드 가독성 향상
- 로그아웃 API 주소를 실제 사용되는 엔드포인트로 수정
- 로그인 후 API 요청 시 Content Type을 수동으로 명시 가능하게 설정
- 명시하지 않았을 시, Content-Type: application/json 헤더가 자동으로 설정되도록 공통 설정 로직 추가
-
-
> Fix(#4)/ 인증 토큰 처리 및 API 요청 설정 수정

- .github/workflows/deploy.yml
- Dockerfile
> #102
> .env 파일을 docker working dir에 포함 시키기
> Fix(#102): to apply .env to right directory

- .github/workflows/deploy.yml
> #102
> .env 파일을 docker working dir에 포함 시키기
> HotFix(#102): to apply .env to right directory

- src/app/api/auth/refresh/route.js
- src/app/api/signin/route.js
> #4 #102 
> 프로덕션 환경에 따른 쿠키 도메인 설정 추가
-
-
> Fix: 프로덕션 환경에 따른 쿠키 도메인 설정 추가 #4

- src/app/recruit/screen/Recruit11.jsx
#16
회원 모집 폼중 마지막 입금계좌 안내문구를 기존 카카오뱅크 -> 토스뱅크로 수정함.
>
> Fix: 입금 계좌 정보 변경

- .github/workflows/deploy.yml
- next.config.ts
- package.json
- yarn.lock
> Fix: webpack 설정 추가 및 불필요한 export 스크립트 제거

- .github/workflows/deploy.yml
> Fix: deploy.yml에서 NODE_ENV 환경 변수 제거

- src/app/test/page.jsx
> Feat: 로그인 테스트 페이지에 cicd 배포 테스트 메시지 추가

- src/app/admin/page.jsx
- src/components/admin/AdminTableBottomContent.jsx
- yarn.lock
#6 
- 모바일에서 관리자 페이지에서 모달창 닫힐 때 toggle 버튼 같이 눌리는 버그 수정
- 모바일에서 총 가입자 수 텍스트 작아지게 수정
-
-
> Fix(#6)/admin 페이지 모달창 닫힘 버그 개선 및 가입자 수 텍스트 수정

- .github/workflows/deploy.yml
> Chore: deploy.yml에서 브랜치 이름을 'main'에서 'master'로 변경

- .github/workflows/deploy.yml
> Chore: deploy.yml에서 브랜치 이름을 'main'에서 'master'로 수정
